import { z } from 'zod';
import * as v from '@go-short/validation';
import { type Permission, ROLE_PERMISSIONS } from '@go-short/shared';
import { envelope, paged, ref } from './schemas';

type S = Record<string, unknown>;

export type Scope = 'public' | 'session' | 'workspace' | 'admin';

export interface Op {
  method: 'get' | 'post' | 'patch' | 'delete';
  /** Path relative to its mount: `/api/v1` for public/session/admin, the workspace for `workspace` scope. */
  path: string;
  scope: Scope;
  /** Also exposed as a flat route (`/api/v1/links`) for API keys. Only for `workspace` scope. */
  flat?: boolean;
  tag: string;
  summary: string;
  description?: string;
  permission?: Permission;
  body?: z.ZodType;
  /** Raw (non-JSON) request body, e.g. an image upload. */
  rawBody?: { contentTypes: string[]; description: string };
  query?: z.ZodType;
  status?: number;
  response?: S;
  /** Non-JSON response. */
  binary?: { contentTypes: string[]; description: string };
  /** Response is not wrapped in `{ success, data }` (health checks). */
  bare?: boolean;
}

const E = envelope;
const tokenBody = z.object({ token: z.string().min(20).max(200) });
const arr = (name: string): S => ({ type: 'array', items: ref(name) });
const OK = ref('Empty');

/** Lowest role that holds a permission, for the generated documentation text. */
export function minimumRole(p: Permission): string {
  for (const r of ['VIEWER', 'MEMBER', 'ADMIN', 'OWNER'] as const)
    if (ROLE_PERMISSIONS[r].has(p)) return r;
  return 'OWNER';
}

export const operations: Op[] = [
  // ---- health --------------------------------------------------------------------------------
  {
    method: 'get',
    path: '/health',
    scope: 'public',
    tag: 'Health',
    summary: 'Liveness check',
    bare: true,
    response: ref('Health'),
  },
  {
    method: 'get',
    path: '/ready',
    scope: 'public',
    tag: 'Health',
    summary: 'Readiness check (PostgreSQL and Redis)',
    description:
      'Returns 503 with per-dependency pass/fail when a dependency is unavailable. No hostnames or error text are exposed.',
    bare: true,
    response: ref('Ready'),
  },

  // ---- auth ----------------------------------------------------------------------------------
  {
    method: 'post',
    path: '/auth/register',
    scope: 'public',
    tag: 'Auth',
    summary: 'Create an account',
    description:
      'Signs the new user in (sets the session cookie) and returns the CSRF token. Rate limited: 10 attempts / 15 min / IP across credential endpoints.',
    body: v.registerSchema,
    status: 201,
    response: ref('AuthResult'),
  },
  {
    method: 'post',
    path: '/auth/login',
    scope: 'public',
    tag: 'Auth',
    summary: 'Sign in',
    description:
      'Sets an httpOnly session cookie. The response `csrfToken` must be sent as `X-CSRF-Token` on every unsafe request made with the cookie.',
    body: v.loginSchema,
    response: ref('AuthResult'),
  },
  {
    method: 'post',
    path: '/auth/logout',
    scope: 'session',
    tag: 'Auth',
    summary: 'Sign out',
    response: OK,
  },
  {
    method: 'post',
    path: '/auth/change-password',
    scope: 'session',
    tag: 'Auth',
    summary: 'Change password',
    description: 'Signs out all other devices.',
    body: v.changePasswordSchema,
    response: OK,
  },
  {
    method: 'post',
    path: '/auth/forgot-password',
    scope: 'public',
    tag: 'Auth',
    summary: 'Request a password reset email',
    description: 'Always returns 200, whether or not the email is registered.',
    body: v.forgotPasswordSchema,
    response: OK,
  },
  {
    method: 'post',
    path: '/auth/reset-password',
    scope: 'public',
    tag: 'Auth',
    summary: 'Reset a password with an emailed token',
    description: 'Single-use token. Signs out every session.',
    body: v.resetPasswordSchema,
    response: OK,
  },
  {
    method: 'post',
    path: '/auth/verify-email',
    scope: 'public',
    tag: 'Auth',
    summary: 'Verify an email address',
    body: tokenBody,
    response: OK,
  },
  {
    method: 'get',
    path: '/me',
    scope: 'session',
    tag: 'Auth',
    summary: 'The signed-in user, CSRF token and workspaces',
    response: ref('Me'),
  },

  // ---- workspaces ----------------------------------------------------------------------------
  {
    method: 'get',
    path: '/workspaces',
    scope: 'session',
    tag: 'Workspaces',
    summary: 'List my workspaces',
    response: arr('WorkspaceWithRole'),
  },
  {
    method: 'post',
    path: '/workspaces',
    scope: 'session',
    tag: 'Workspaces',
    summary: 'Create a workspace',
    description: 'The creator becomes OWNER. Limited to 20 per hour.',
    body: v.createWorkspaceSchema,
    status: 201,
    response: ref('WorkspaceWithRole'),
  },
  {
    method: 'post',
    path: '/workspaces/invitations/accept',
    scope: 'session',
    tag: 'Workspaces',
    summary: 'Accept a workspace invitation',
    description: 'The token must have been issued to the signed-in user’s email address.',
    body: tokenBody,
    response: {
      type: 'object',
      properties: { workspaceId: { type: 'string' } },
      required: ['workspaceId'],
      additionalProperties: false,
    },
  },
  {
    method: 'get',
    path: '/workspaces/{workspaceId}',
    scope: 'workspace',
    tag: 'Workspaces',
    summary: 'Get the workspace',
    permission: 'workspace:read',
    response: ref('WorkspaceWithRole'),
  },
  {
    method: 'patch',
    path: '/workspaces/{workspaceId}',
    scope: 'workspace',
    tag: 'Workspaces',
    summary: 'Update workspace settings',
    description:
      'Includes the analytics privacy settings: `hashIps`, `filterBots`, `retentionDays` (null = keep forever) and the default `timezone`.',
    permission: 'workspace:update',
    body: v.updateWorkspaceSchema,
    response: ref('Workspace'),
  },
  {
    method: 'delete',
    path: '/workspaces/{workspaceId}',
    scope: 'workspace',
    tag: 'Workspaces',
    summary: 'Delete the workspace and everything in it',
    permission: 'workspace:delete',
    response: OK,
  },
  {
    method: 'get',
    path: '/workspaces/{workspaceId}/overview',
    scope: 'workspace',
    tag: 'Workspaces',
    summary: 'Workspace totals (links, campaigns, QR codes, domains, members)',
    permission: 'workspace:read',
    response: ref('Overview'),
  },
  {
    method: 'get',
    path: '/workspaces/{workspaceId}/members',
    scope: 'workspace',
    tag: 'Members',
    summary: 'List members',
    permission: 'members:read',
    response: arr('Member'),
  },
  {
    method: 'post',
    path: '/workspaces/{workspaceId}/members/invite',
    scope: 'workspace',
    tag: 'Members',
    summary: 'Invite a member by email',
    description:
      'You cannot grant a role above your own. A new invitation replaces any pending one for the same address. 30 per hour per workspace.',
    permission: 'members:manage',
    body: v.inviteMemberSchema,
    status: 201,
    response: ref('Invitation'),
  },
  {
    method: 'patch',
    path: '/workspaces/{workspaceId}/members/{memberId}',
    scope: 'workspace',
    tag: 'Members',
    summary: 'Change a member’s role',
    description:
      'A workspace always keeps at least one OWNER. Demoting a member to VIEWER also caps their API keys to read-only.',
    permission: 'members:manage',
    body: v.updateMemberSchema,
    response: {
      type: 'object',
      properties: { id: { type: 'string' }, role: { type: 'string' } },
      required: ['id', 'role'],
      additionalProperties: false,
    },
  },
  {
    method: 'delete',
    path: '/workspaces/{workspaceId}/members/{memberId}',
    scope: 'workspace',
    tag: 'Members',
    summary: 'Remove a member (or leave)',
    description:
      'Any member may remove themselves; removing others needs `members:manage`. Revokes the member’s API keys.',
    permission: 'workspace:read',
    response: OK,
  },
  {
    method: 'get',
    path: '/workspaces/{workspaceId}/audit-logs',
    scope: 'workspace',
    tag: 'Audit',
    summary: 'Audit log (cursor-paginated, newest first)',
    permission: 'audit:read',
    query: v.cursorQuery,
    response: { type: 'array', items: ref('AuditLog') },
  },

  // ---- domains -------------------------------------------------------------------------------
  {
    method: 'get',
    path: '/domains',
    scope: 'workspace',
    flat: true,
    tag: 'Domains',
    summary: 'List domains',
    description:
      'The workspace’s own domains plus the platform-shared default domain (`shared: true`).',
    permission: 'domains:read',
    response: arr('Domain'),
  },
  {
    method: 'post',
    path: '/domains',
    scope: 'workspace',
    flat: true,
    tag: 'Domains',
    summary: 'Add a custom domain',
    description:
      'Returns DNS instructions (CNAME and TXT). The domain is `PENDING` until verified. A hostname can belong to only one workspace.',
    permission: 'domains:manage',
    body: v.createDomainSchema,
    status: 201,
    response: ref('Domain'),
  },
  {
    method: 'get',
    path: '/domains/{domainId}',
    scope: 'workspace',
    flat: true,
    tag: 'Domains',
    summary: 'Get a domain',
    permission: 'domains:read',
    response: ref('Domain'),
  },
  {
    method: 'post',
    path: '/domains/{domainId}/verify',
    scope: 'workspace',
    flat: true,
    tag: 'Domains',
    summary: 'Check DNS and verify the domain',
    description:
      'Verifies via a CNAME to the platform host or a TXT record `_goshort-verify.<hostname>`. Returns `verified: false` (200) when DNS is not ready yet. 10 per minute.',
    permission: 'domains:manage',
    response: ref('DomainVerification'),
  },
  {
    method: 'patch',
    path: '/domains/{domainId}',
    scope: 'workspace',
    flat: true,
    tag: 'Domains',
    summary: 'Set default or disable/enable a domain',
    description: 'Disabling a domain purges its cached redirects.',
    permission: 'domains:manage',
    body: v.updateDomainSchema,
    response: ref('Domain'),
  },
  {
    method: 'delete',
    path: '/domains/{domainId}',
    scope: 'workspace',
    flat: true,
    tag: 'Domains',
    summary: 'Delete a domain',
    description: 'Refused (409) while the domain still has links.',
    permission: 'domains:manage',
    response: OK,
  },

  // ---- links ---------------------------------------------------------------------------------
  {
    method: 'get',
    path: '/links',
    scope: 'workspace',
    flat: true,
    tag: 'Links',
    summary: 'List links (cursor-paginated, newest first)',
    permission: 'links:read',
    query: v.listLinksQuery,
    response: { type: 'array', items: ref('Link') },
  },
  {
    method: 'post',
    path: '/links',
    scope: 'workspace',
    flat: true,
    tag: 'Links',
    summary: 'Create a link',
    description:
      'Omit `slug` for a random 7-character slug. Destinations must be http(s) and may not point at a short-link domain. Limited to 120 per minute per workspace.',
    permission: 'links:write',
    body: v.createLinkSchema,
    status: 201,
    response: ref('Link'),
  },
  {
    method: 'get',
    path: '/links/{linkId}',
    scope: 'workspace',
    flat: true,
    tag: 'Links',
    summary: 'Get a link',
    permission: 'links:read',
    response: ref('Link'),
  },
  {
    method: 'patch',
    path: '/links/{linkId}',
    scope: 'workspace',
    flat: true,
    tag: 'Links',
    summary: 'Update a link',
    description: 'Redirect caches for the old and new location are invalidated immediately.',
    permission: 'links:write',
    body: v.updateLinkSchema,
    response: ref('Link'),
  },
  {
    method: 'delete',
    path: '/links/{linkId}',
    scope: 'workspace',
    flat: true,
    tag: 'Links',
    summary: 'Delete a link (and its QR codes)',
    permission: 'links:delete',
    response: OK,
  },
  {
    method: 'post',
    path: '/links/{linkId}/enable',
    scope: 'workspace',
    flat: true,
    tag: 'Links',
    summary: 'Enable a link',
    permission: 'links:write',
    response: ref('Link'),
  },
  {
    method: 'post',
    path: '/links/{linkId}/disable',
    scope: 'workspace',
    flat: true,
    tag: 'Links',
    summary: 'Disable a link',
    description: 'A disabled link answers `410 Gone`.',
    permission: 'links:write',
    response: ref('Link'),
  },
  {
    method: 'get',
    path: '/links/{linkId}/analytics',
    scope: 'workspace',
    flat: true,
    tag: 'Analytics',
    summary: 'Analytics for one link',
    description: 'See the Analytics tag description for parameters, timezones and accuracy.',
    permission: 'analytics:read',
    query: v.analyticsQuery,
    response: ref('Analytics'),
  },
  {
    method: 'get',
    path: '/links/{linkId}/analytics/export',
    scope: 'workspace',
    flat: true,
    tag: 'Analytics',
    summary: 'Export one link’s analytics as CSV',
    permission: 'analytics:export',
    query: v.exportQuery,
    binary: { contentTypes: ['text/csv'], description: 'Streamed CSV.' },
  },

  // ---- campaigns -----------------------------------------------------------------------------
  {
    method: 'get',
    path: '/campaigns',
    scope: 'workspace',
    flat: true,
    tag: 'Campaigns',
    summary: 'List campaigns',
    permission: 'campaigns:read',
    query: v.listCampaignsQuery,
    response: { type: 'array', items: ref('Campaign') },
  },
  {
    method: 'post',
    path: '/campaigns',
    scope: 'workspace',
    flat: true,
    tag: 'Campaigns',
    summary: 'Create a campaign',
    permission: 'campaigns:write',
    body: v.createCampaignSchema,
    status: 201,
    response: ref('Campaign'),
  },
  {
    method: 'get',
    path: '/campaigns/{campaignId}',
    scope: 'workspace',
    flat: true,
    tag: 'Campaigns',
    summary: 'Get a campaign',
    permission: 'campaigns:read',
    response: ref('Campaign'),
  },
  {
    method: 'patch',
    path: '/campaigns/{campaignId}',
    scope: 'workspace',
    flat: true,
    tag: 'Campaigns',
    summary: 'Update a campaign',
    permission: 'campaigns:write',
    body: v.updateCampaignSchema,
    response: ref('Campaign'),
  },
  {
    method: 'delete',
    path: '/campaigns/{campaignId}',
    scope: 'workspace',
    flat: true,
    tag: 'Campaigns',
    summary: 'Delete a campaign',
    description: 'Its links and QR codes are kept and become campaign-less.',
    permission: 'campaigns:delete',
    response: OK,
  },
  {
    method: 'get',
    path: '/campaigns/{campaignId}/analytics',
    scope: 'workspace',
    flat: true,
    tag: 'Analytics',
    summary: 'Analytics for a campaign',
    permission: 'analytics:read',
    query: v.analyticsQuery,
    response: ref('Analytics'),
  },
  {
    method: 'get',
    path: '/campaigns/{campaignId}/analytics/export',
    scope: 'workspace',
    flat: true,
    tag: 'Analytics',
    summary: 'Export a campaign’s analytics as CSV',
    permission: 'analytics:export',
    query: v.exportQuery,
    binary: { contentTypes: ['text/csv'], description: 'Streamed CSV.' },
  },

  // ---- QR codes ------------------------------------------------------------------------------
  {
    method: 'get',
    path: '/qr',
    scope: 'workspace',
    flat: true,
    tag: 'QR codes',
    summary: 'List QR codes',
    permission: 'qr:read',
    query: v.listQrQuery,
    response: { type: 'array', items: ref('Qr') },
  },
  {
    method: 'post',
    path: '/qr',
    scope: 'workspace',
    flat: true,
    tag: 'QR codes',
    summary: 'Create a QR code and get the generated image',
    description:
      'Generated locally. The code encodes the link’s short URL plus a `?qr=<id>` marker so scans are counted separately. Colours must be `#RRGGBB`, dark-on-light with at least 3:1 contrast; a logo forces error correction `H`.',
    permission: 'qr:write',
    body: v.createQrSchema,
    status: 201,
    response: ref('QrWithImage'),
  },
  {
    method: 'post',
    path: '/qr/logos',
    scope: 'workspace',
    flat: true,
    tag: 'QR codes',
    summary: 'Upload a QR logo',
    description:
      'Raw request body, `Content-Type: image/png` or `image/jpeg`, max 512 KB, max 2048×2048. The image is re-encoded as a sanitized PNG (metadata stripped, scaled to ≤256 px). Pass the returned `logoPath` when creating or updating a QR code. 30 per hour.',
    permission: 'qr:write',
    rawBody: { contentTypes: ['image/png', 'image/jpeg'], description: 'The image bytes.' },
    status: 201,
    response: ref('QrLogo'),
  },
  {
    method: 'post',
    path: '/qr/preview',
    scope: 'workspace',
    flat: true,
    tag: 'QR codes',
    summary: 'Render a QR code without saving it',
    description:
      'Stateless preview used by the designer: same options as creation, returns the image bytes and persists nothing. 240 per minute.',
    permission: 'qr:read',
    body: v.previewQrSchema,
    binary: { contentTypes: ['image/svg+xml', 'image/png'], description: 'The QR image.' },
  },
  {
    method: 'get',
    path: '/qr/{qrId}',
    scope: 'workspace',
    flat: true,
    tag: 'QR codes',
    summary: 'Get QR code metadata',
    permission: 'qr:read',
    response: ref('Qr'),
  },
  {
    method: 'get',
    path: '/qr/{qrId}/image',
    scope: 'workspace',
    flat: true,
    tag: 'QR codes',
    summary: 'Download the QR image',
    description:
      'Query parameters override the stored `format` and `size`. With `download=1` the response is an attachment.',
    permission: 'qr:read',
    query: v.qrImageQuery,
    binary: { contentTypes: ['image/svg+xml', 'image/png'], description: 'The QR image.' },
  },
  {
    method: 'patch',
    path: '/qr/{qrId}',
    scope: 'workspace',
    flat: true,
    tag: 'QR codes',
    summary: 'Update a QR code',
    permission: 'qr:write',
    body: v.updateQrSchema,
    response: ref('Qr'),
  },
  {
    method: 'delete',
    path: '/qr/{qrId}',
    scope: 'workspace',
    flat: true,
    tag: 'QR codes',
    summary: 'Delete a QR code',
    permission: 'qr:write',
    response: OK,
  },

  // ---- analytics -----------------------------------------------------------------------------
  {
    method: 'get',
    path: '/analytics',
    scope: 'workspace',
    flat: true,
    tag: 'Analytics',
    summary: 'Workspace analytics',
    description: 'Optionally filter with `linkId`, `campaignId`, `country`, `device`.',
    permission: 'analytics:read',
    query: v.analyticsQuery,
    response: ref('Analytics'),
  },
  {
    method: 'get',
    path: '/analytics/export',
    scope: 'workspace',
    flat: true,
    tag: 'Analytics',
    summary: 'Export analytics as CSV',
    description:
      '`type=daily` (rollup rows) or `type=events` (raw clicks without IPs or visitor ids, max 1,000,000 rows). Streamed; spreadsheet formulas are neutralized. 5 per minute per workspace.',
    permission: 'analytics:export',
    query: v.exportQuery,
    binary: { contentTypes: ['text/csv'], description: 'Streamed CSV.' },
  },

  // ---- API keys ------------------------------------------------------------------------------
  {
    method: 'get',
    path: '/workspaces/{workspaceId}/api-keys',
    scope: 'workspace',
    tag: 'API keys',
    summary: 'List API keys',
    description:
      'Session only: an API key cannot manage API keys. Only the public prefix is shown.',
    permission: 'apikeys:manage',
    response: arr('ApiKey'),
  },
  {
    method: 'post',
    path: '/workspaces/{workspaceId}/api-keys',
    scope: 'workspace',
    tag: 'API keys',
    summary: 'Create an API key',
    description:
      'The full key is returned **once**. Keys are VIEWER (read-only) or MEMBER (read/write), bound to this workspace, never ADMIN/OWNER. At most 50 active keys per workspace.',
    permission: 'apikeys:manage',
    body: v.createApiKeySchema,
    status: 201,
    response: ref('ApiKeyCreated'),
  },
  {
    method: 'delete',
    path: '/workspaces/{workspaceId}/api-keys/{keyId}',
    scope: 'workspace',
    tag: 'API keys',
    summary: 'Revoke an API key',
    description: 'Takes effect immediately. Idempotent.',
    permission: 'apikeys:manage',
    response: OK,
  },

  // ---- webhooks ------------------------------------------------------------------------------
  {
    method: 'get',
    path: '/workspaces/{workspaceId}/webhooks',
    scope: 'workspace',
    tag: 'Webhooks',
    summary: 'List webhooks',
    description: 'Session only.',
    permission: 'webhooks:manage',
    response: arr('Webhook'),
  },
  {
    method: 'post',
    path: '/workspaces/{workspaceId}/webhooks',
    scope: 'workspace',
    tag: 'Webhooks',
    summary: 'Create a webhook',
    description:
      'The signing secret is returned **once**. URLs must be https and public (SSRF-protected at delivery). At most 10 per workspace.',
    permission: 'webhooks:manage',
    body: v.createWebhookSchema,
    status: 201,
    response: ref('WebhookCreated'),
  },
  {
    method: 'patch',
    path: '/workspaces/{workspaceId}/webhooks/{webhookId}',
    scope: 'workspace',
    tag: 'Webhooks',
    summary: 'Update a webhook',
    permission: 'webhooks:manage',
    body: v.updateWebhookSchema,
    response: ref('Webhook'),
  },
  {
    method: 'post',
    path: '/workspaces/{workspaceId}/webhooks/{webhookId}/rotate-secret',
    scope: 'workspace',
    tag: 'Webhooks',
    summary: 'Rotate the signing secret',
    permission: 'webhooks:manage',
    response: ref('WebhookSecret'),
  },
  {
    method: 'post',
    path: '/workspaces/{workspaceId}/webhooks/{webhookId}/test',
    scope: 'workspace',
    tag: 'Webhooks',
    summary: 'Queue a test delivery',
    permission: 'webhooks:manage',
    status: 202,
    response: {
      type: 'object',
      properties: { deliveryId: { type: 'string' } },
      required: ['deliveryId'],
      additionalProperties: false,
    },
  },
  {
    method: 'delete',
    path: '/workspaces/{workspaceId}/webhooks/{webhookId}',
    scope: 'workspace',
    tag: 'Webhooks',
    summary: 'Delete a webhook',
    permission: 'webhooks:manage',
    response: OK,
  },

  // ---- admin ---------------------------------------------------------------------------------
  {
    method: 'get',
    path: '/admin/stats',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Platform overview',
    response: ref('AdminStats'),
  },
  {
    method: 'get',
    path: '/admin/users',
    scope: 'admin',
    tag: 'Admin',
    summary: 'List users (no secrets)',
    query: v.adminListQuery,
    response: { type: 'array', items: ref('AdminUser') },
  },
  {
    method: 'post',
    path: '/admin/auth/login',
    scope: 'public',
    tag: 'Admin',
    summary: 'Sign in to the console (staff only)',
    description:
      'Separate from the app sign-in: sets the `gs_console` cookie (8 hours, sent only to `/api/v1/admin`), which the app never accepts, and the app cookie never opens the console. Needs a platform role.',
    body: v.loginSchema,
    response: ref('ConsoleSession'),
  },
  {
    method: 'post',
    path: '/admin/auth/logout',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Sign out of the console',
    response: OK,
  },
  {
    method: 'get',
    path: '/admin/me',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Who am I in the console (role, capabilities, monitoring links)',
    response: ref('ConsoleMe'),
  },
  {
    method: 'get',
    path: '/admin/usage',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Platform usage analytics (signups, workspaces, links, clicks, top workspaces)',
    query: v.usageQuery,
    response: ref('Usage'),
  },
  {
    method: 'get',
    path: '/admin/users/{userId}',
    scope: 'admin',
    tag: 'Admin',
    summary: 'User detail (memberships, sessions, key count; no secrets)',
    response: ref('AdminUserDetail'),
  },
  {
    method: 'post',
    path: '/admin/users/{userId}/disable',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Suspend an account',
    description:
      "Ends every session and stops the account's API keys. Needs the admin role; only a super admin can suspend staff, and the last active super admin cannot be suspended.",
    response: ref('UserDisabled'),
  },
  {
    method: 'post',
    path: '/admin/users/{userId}/enable',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Re-enable a suspended account',
    response: ref('UserDisabled'),
  },
  {
    method: 'get',
    path: '/admin/workspaces/{workspaceId}',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Workspace detail (members, domains, counts, clicks)',
    response: ref('AdminWorkspaceDetail'),
  },
  {
    method: 'get',
    path: '/admin/teams',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Every workspace membership on the platform',
    query: v.teamsQuery,
    response: arr('AdminTeamMember'),
  },
  {
    method: 'get',
    path: '/admin/staff',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Platform staff (managers, admins, super admins)',
    response: arr('StaffMember'),
  },
  {
    method: 'post',
    path: '/admin/staff',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Give an existing account a platform role',
    description: 'Super admin only. The person must already have an account.',
    body: v.addStaffSchema,
    status: 201,
    response: ref('StaffMember'),
  },
  {
    method: 'patch',
    path: '/admin/staff/{userId}',
    scope: 'admin',
    tag: 'Admin',
    summary: "Change a staff member's platform role",
    description:
      'Super admin only. You cannot change your own role, and the last active super admin cannot be demoted.',
    body: v.updateStaffSchema,
    response: ref('StaffMember'),
  },
  {
    method: 'delete',
    path: '/admin/staff/{userId}',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Remove platform access',
    description: 'Super admin only. The account itself is kept; it becomes an ordinary user.',
    response: OK,
  },
  {
    method: 'get',
    path: '/admin/monitoring',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Platform health metrics from Prometheus (fixed set)',
    response: ref('Monitoring'),
  },
  {
    method: 'get',
    path: '/admin/monitoring/range',
    scope: 'admin',
    tag: 'Admin',
    summary: 'A metric over time',
    description:
      '`query` is one of the metric names from `GET /admin/monitoring`; arbitrary PromQL is not accepted.',
    query: v.monitoringRangeQuery,
    response: ref('MetricRange'),
  },
  {
    method: 'get',
    path: '/admin/workspaces',
    scope: 'admin',
    tag: 'Admin',
    summary: 'List workspaces',
    query: v.adminListQuery,
    response: { type: 'array', items: ref('AdminWorkspace') },
  },
  {
    method: 'get',
    path: '/admin/domains',
    scope: 'admin',
    tag: 'Admin',
    summary: 'List domains',
    query: v.adminListQuery,
    response: { type: 'array', items: ref('AdminDomain') },
  },
  {
    method: 'get',
    path: '/admin/links',
    scope: 'admin',
    tag: 'Admin',
    summary: 'List links across workspaces',
    query: v.adminListQuery,
    response: { type: 'array', items: ref('AdminLink') },
  },
  {
    method: 'get',
    path: '/admin/audit-logs',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Audit logs across workspaces',
    query: v.adminListQuery,
    response: { type: 'array', items: ref('AdminAuditLog') },
  },
  {
    method: 'get',
    path: '/admin/queues',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Queue job counts',
    response: ref('QueueCounts'),
  },
  {
    method: 'get',
    path: '/admin/queues/{queue}/failed',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Failed jobs (dead letter) of a queue',
    description:
      'Job payloads are summarized, never returned: analytics jobs contain raw IP addresses.',
    response: arr('FailedJob'),
  },
  {
    method: 'post',
    path: '/admin/queues/{queue}/failed/{jobId}/retry',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Retry a failed job',
    response: OK,
  },
  {
    method: 'delete',
    path: '/admin/queues/{queue}/failed/{jobId}',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Delete a failed job',
    response: OK,
  },
  {
    method: 'post',
    path: '/admin/cleanup/{task}/run',
    scope: 'admin',
    tag: 'Admin',
    summary: 'Run a cleanup task now',
    status: 202,
    response: {
      type: 'object',
      properties: { task: { type: 'string' } },
      required: ['task'],
      additionalProperties: false,
    },
  },
];

export { E, paged };
