/** Reusable JSON Schemas (OpenAPI 3.1 / JSON Schema 2020-12) for response bodies. Kept honest by test/openapi.test.ts, which validates real responses against them. */
type S = Record<string, unknown>;

const str = (extra: S = {}): S => ({ type: 'string', ...extra });
const nullable = (s: S): S => ({ anyOf: [s, { type: 'null' }] });
const dateTime = (): S => str({ format: 'date-time' });
const obj = (
  properties: Record<string, S>,
  required: string[] = Object.keys(properties),
  extra: S = {},
): S => ({
  type: 'object',
  properties,
  required,
  additionalProperties: false,
  ...extra,
});
const arr = (items: S): S => ({ type: 'array', items });
const int = (extra: S = {}): S => ({ type: 'integer', ...extra });
const role = (): S => ({ type: 'string', enum: ['OWNER', 'ADMIN', 'MEMBER', 'VIEWER'] });

export const schemas: Record<string, S> = {
  Error: obj(
    {
      success: { const: false },
      error: obj(
        { code: str(), message: str(), details: { type: 'array', items: { type: 'object' } } },
        ['code', 'message'],
      ),
      requestId: str(),
    },
    ['success', 'error', 'requestId'],
  ),
  Empty: obj({}),
  User: obj({
    id: str(),
    email: str({ format: 'email' }),
    name: str(),
    emailVerified: { type: 'boolean' },
    systemRole: { type: 'string', enum: ['USER', 'MANAGER', 'ADMIN', 'SUPER_ADMIN'] },
  }),
  AuthResult: obj({ user: { $ref: '#/components/schemas/User' }, csrfToken: str() }),
  Me: obj({
    user: { $ref: '#/components/schemas/User' },
    csrfToken: str(),
    workspaces: arr(obj({ id: str(), name: str(), slug: str(), role: role() })),
  }),
  Workspace: obj({
    id: str(),
    name: str(),
    slug: str(),
    timezone: str(),
    hashIps: { type: 'boolean' },
    filterBots: { type: 'boolean' },
    retentionDays: nullable(int({ minimum: 1 })),
    createdAt: dateTime(),
  }),
  WorkspaceWithRole: obj({
    id: str(),
    name: str(),
    slug: str(),
    timezone: str(),
    hashIps: { type: 'boolean' },
    filterBots: { type: 'boolean' },
    retentionDays: nullable(int({ minimum: 1 })),
    createdAt: dateTime(),
    role: role(),
  }),
  Member: obj({
    id: str(),
    role: role(),
    createdAt: dateTime(),
    user: obj({ id: str(), email: str(), name: str() }),
  }),
  Invitation: obj({ id: str(), email: str(), role: role(), expiresAt: dateTime() }),
  AuditLog: obj(
    {
      id: str(),
      workspaceId: nullable(str()),
      userId: nullable(str()),
      action: str(),
      resourceType: str(),
      resourceId: nullable(str()),
      metadata: {},
      createdAt: dateTime(),
    },
    ['id', 'workspaceId', 'userId', 'action', 'resourceType', 'resourceId', 'createdAt'],
  ),
  Domain: obj({
    id: str(),
    hostname: str(),
    status: { type: 'string', enum: ['PENDING', 'VERIFIED', 'DISABLED'] },
    isVerified: { type: 'boolean' },
    isDefault: { type: 'boolean' },
    shared: { type: 'boolean' },
    createdAt: dateTime(),
    dns: nullable(
      obj({
        cname: obj({ type: str(), name: str(), value: str() }),
        txt: obj({ type: str(), name: str(), value: str() }),
      }),
    ),
  }),
  DomainVerification: obj(
    {
      verified: { type: 'boolean' },
      method: { type: 'string', enum: ['CNAME', 'TXT'] },
      domain: { $ref: '#/components/schemas/Domain' },
    },
    ['verified', 'domain'],
  ),
  Link: obj({
    id: str(),
    domainId: str(),
    hostname: str(),
    slug: str(),
    shortUrl: str(),
    destinationUrl: str(),
    title: nullable(str()),
    description: nullable(str()),
    campaignId: nullable(str()),
    isActive: { type: 'boolean' },
    expiresAt: nullable(dateTime()),
    expired: { type: 'boolean' },
    hasPassword: { type: 'boolean' },
    redirectStatus: nullable({ type: 'integer', enum: [301, 302, 307, 308] }),
    utmSource: nullable(str()),
    utmMedium: nullable(str()),
    utmCampaign: nullable(str()),
    utmTerm: nullable(str()),
    utmContent: nullable(str()),
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  Campaign: obj({
    id: str(),
    name: str(),
    description: nullable(str()),
    startDate: nullable(dateTime()),
    endDate: nullable(dateTime()),
    utmCampaign: nullable(str()),
    linkCount: int(),
    qrCodeCount: int(),
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  Qr: obj({
    id: str(),
    name: str(),
    linkId: str(),
    campaignId: nullable(str()),
    format: { type: 'string', enum: ['svg', 'png'] },
    size: int(),
    margin: int(),
    errorCorrection: { type: 'string', enum: ['L', 'M', 'Q', 'H'] },
    foregroundColor: str(),
    backgroundColor: str(),
    hasLogo: { type: 'boolean' },
    url: str({
      description: 'The URL encoded in the QR code: the short URL plus a ?qr=<id> scan marker.',
    }),
    createdAt: dateTime(),
    updatedAt: dateTime(),
  }),
  QrWithImage: obj({
    id: str(),
    name: str(),
    linkId: str(),
    campaignId: nullable(str()),
    format: { type: 'string', enum: ['svg', 'png'] },
    size: int(),
    margin: int(),
    errorCorrection: { type: 'string', enum: ['L', 'M', 'Q', 'H'] },
    foregroundColor: str(),
    backgroundColor: str(),
    hasLogo: { type: 'boolean' },
    url: str(),
    createdAt: dateTime(),
    updatedAt: dateTime(),
    mimeType: { type: 'string', enum: ['image/svg+xml', 'image/png'] },
    encoding: { type: 'string', enum: ['utf8', 'base64'] },
    data: str({ description: 'SVG markup (utf8) or base64-encoded PNG.' }),
  }),
  QrLogo: obj({ logoPath: str(), bytes: int() }),
  ApiKey: obj(
    {
      id: str(),
      name: str(),
      keyPrefix: str(),
      role: { type: 'string', enum: ['VIEWER', 'MEMBER'] },
      createdAt: dateTime(),
      lastUsedAt: nullable(dateTime()),
      expiresAt: nullable(dateTime()),
      revokedAt: nullable(dateTime()),
      createdBy: obj({ id: str(), name: str() }),
    },
    ['id', 'name', 'keyPrefix', 'role', 'createdAt', 'lastUsedAt', 'expiresAt', 'revokedAt'],
  ),
  ApiKeyCreated: obj({
    id: str(),
    name: str(),
    keyPrefix: str(),
    role: { type: 'string', enum: ['VIEWER', 'MEMBER'] },
    createdAt: dateTime(),
    lastUsedAt: nullable(dateTime()),
    expiresAt: nullable(dateTime()),
    revokedAt: nullable(dateTime()),
    key: str({ description: 'The full API key. Returned ONLY in this response; store it now.' }),
  }),
  Webhook: obj({
    id: str(),
    url: str(),
    events: arr(str()),
    isActive: { type: 'boolean' },
    createdAt: dateTime(),
  }),
  WebhookCreated: obj({
    id: str(),
    url: str(),
    events: arr(str()),
    isActive: { type: 'boolean' },
    createdAt: dateTime(),
    secret: str({
      description: 'Signing secret. Returned ONLY in this response; rotate it if lost.',
    }),
  }),
  WebhookSecret: obj({ id: str(), secret: str() }),
  Breakdown: arr(
    obj({ value: str(), clicks: int() }, ['value', 'clicks'], { additionalProperties: true }),
  ),
  Analytics: obj({
    summary: obj({
      clicks: int(),
      humanClicks: int(),
      botClicks: int(),
      uniqueVisitors: int({ description: 'Approximate.' }),
      qrScans: int(),
    }),
    timeline: arr(obj({ date: str(), clicks: int(), humanClicks: int(), botClicks: int() })),
    countries: { $ref: '#/components/schemas/Breakdown' },
    regions: { $ref: '#/components/schemas/Breakdown' },
    cities: { $ref: '#/components/schemas/Breakdown' },
    devices: { $ref: '#/components/schemas/Breakdown' },
    browsers: { $ref: '#/components/schemas/Breakdown' },
    os: { $ref: '#/components/schemas/Breakdown' },
    referrers: { $ref: '#/components/schemas/Breakdown' },
    utmSources: { $ref: '#/components/schemas/Breakdown' },
    utmMediums: { $ref: '#/components/schemas/Breakdown' },
    utmCampaigns: { $ref: '#/components/schemas/Breakdown' },
    qrCodes: arr(obj({ value: str(), clicks: int(), name: nullable(str()) })),
    topLinks: arr(
      obj({
        linkId: str(),
        clicks: int(),
        slug: nullable(str()),
        title: nullable(str()),
        hostname: nullable(str()),
        deleted: { type: 'boolean' },
      }),
    ),
    meta: obj({
      timezone: str(),
      from: str(),
      to: str(),
      granularity: { type: 'string', enum: ['day', 'hour'] },
      includeBots: { type: 'boolean' },
      source: { type: 'string', enum: ['rollup', 'events'] },
      notes: arr(str()),
    }),
  }),
  Overview: obj({ links: int(), campaigns: int(), qrCodes: int(), domains: int(), members: int() }),
  Health: obj({ status: str() }),
  Ready: obj({ status: str(), checks: obj({ postgres: str(), redis: str() }) }),
  AdminStats: obj({
    users: int(),
    workspaces: int(),
    domains: int(),
    links: int(),
    qrCodes: int(),
    campaigns: int(),
    clickEventsEstimate: int(),
    queues: {
      type: 'object',
      additionalProperties: { type: 'object', additionalProperties: int() },
    },
  }),
  AdminUser: obj({
    id: str(),
    email: str(),
    name: str(),
    emailVerified: { type: 'boolean' },
    systemRole: str(),
    disabledAt: nullable(dateTime()),
    createdAt: dateTime(),
    workspaceCount: int(),
  }),
  AdminAuditLog: obj(
    {
      id: str(),
      workspaceId: nullable(str()),
      userId: nullable(str()),
      action: str(),
      resourceType: str(),
      resourceId: nullable(str()),
      metadata: {},
      createdAt: dateTime(),
      actor: nullable(obj({ email: str(), name: str() })),
    },
    ['id', 'workspaceId', 'userId', 'action', 'resourceType', 'resourceId', 'createdAt', 'actor'],
  ),
  ConsoleMe: obj({
    user: obj({ id: str(), email: str(), name: str() }),
    role: { type: 'string', enum: ['MANAGER', 'ADMIN', 'SUPER_ADMIN'] },
    capabilities: arr(str()),
    links: obj({ grafana: nullable(str()), prometheus: nullable(str()) }),
    metricsConfigured: { type: 'boolean' },
    csrfToken: str(),
  }),
  ConsoleSession: obj({
    user: obj({ id: str(), email: str(), name: str() }),
    role: { type: 'string', enum: ['MANAGER', 'ADMIN', 'SUPER_ADMIN'] },
    csrfToken: str(),
  }),
  DailyCount: obj({ date: str(), count: int() }),
  Usage: obj({
    days: int(),
    totals: obj({
      signups: int(),
      workspacesCreated: int(),
      linksCreated: int(),
      clicks: int(),
      activeWorkspaces: int(),
    }),
    signups: arr({ $ref: '#/components/schemas/DailyCount' }),
    workspacesCreated: arr({ $ref: '#/components/schemas/DailyCount' }),
    linksCreated: arr({ $ref: '#/components/schemas/DailyCount' }),
    clicks: arr({ $ref: '#/components/schemas/DailyCount' }),
    topWorkspaces: arr(obj({ workspaceId: str(), name: str(), slug: str(), clicks: int() })),
  }),
  AdminUserDetail: obj({
    id: str(),
    email: str(),
    name: str(),
    emailVerified: { type: 'boolean' },
    systemRole: str(),
    disabledAt: nullable(dateTime()),
    createdAt: dateTime(),
    activeSessions: int(),
    apiKeyCount: int(),
    workspaces: arr(
      obj({ id: str(), name: str(), slug: str(), role: role(), joinedAt: dateTime() }),
    ),
  }),
  AdminWorkspaceDetail: obj({
    id: str(),
    name: str(),
    slug: str(),
    timezone: str(),
    retentionDays: nullable(int()),
    hashIps: { type: 'boolean' },
    filterBots: { type: 'boolean' },
    createdAt: dateTime(),
    clicksLast30Days: int(),
    counts: obj({
      links: int(),
      campaigns: int(),
      qrCodes: int(),
      apiKeys: int(),
      webhooks: int(),
    }),
    members: arr(
      obj({
        userId: str(),
        email: str(),
        name: str(),
        disabled: { type: 'boolean' },
        role: role(),
        joinedAt: dateTime(),
      }),
    ),
    domains: arr(obj({ id: str(), hostname: str(), status: str() })),
  }),
  AdminTeamMember: obj({
    id: str(),
    role: role(),
    joinedAt: dateTime(),
    user: obj({ id: str(), email: str(), name: str(), disabled: { type: 'boolean' } }),
    workspace: obj({ id: str(), name: str(), slug: str() }),
  }),
  StaffMember: obj({
    id: str(),
    email: str(),
    name: str(),
    role: { type: 'string', enum: ['MANAGER', 'ADMIN', 'SUPER_ADMIN'] },
    disabled: { type: 'boolean' },
    createdAt: dateTime(),
  }),
  SharedDomain: obj({
    id: str(),
    hostname: str(),
    status: { type: 'string', enum: ['VERIFIED', 'DISABLED'] },
    isDefault: { type: 'boolean' },
    linkCount: { type: 'integer' },
    createdAt: dateTime(),
  }),
  SharedDomains: obj({
    domains: { type: 'array', items: { $ref: '#/components/schemas/SharedDomain' } },
    cnameTarget: str(),
    appHostname: str(),
  }),
  SharedDomainDns: obj({
    hostname: str(),
    addresses: { type: 'array', items: str() },
    appAddresses: { type: 'array', items: str() },
    result: { type: 'string', enum: ['matches', 'differs', 'not_resolving', 'unknown'] },
  }),
  UserDisabled: obj({ id: str(), disabled: { type: 'boolean' } }),
  MetricValue: obj({
    name: str(),
    label: str(),
    unit: { type: 'string', enum: ['rps', 'ms', 'percent', 'count', 'per_minute'] },
    value: nullable({ type: 'number' }),
  }),
  Monitoring: obj({
    configured: { type: 'boolean' },
    links: obj({ grafana: nullable(str()), prometheus: nullable(str()) }),
    metrics: arr({ $ref: '#/components/schemas/MetricValue' }),
  }),
  MetricRange: obj({
    name: str(),
    label: str(),
    unit: str(),
    minutes: int(),
    points: arr(obj({ t: { type: 'number' }, v: nullable({ type: 'number' }) })),
  }),
  AdminWorkspace: obj({
    id: str(),
    name: str(),
    slug: str(),
    timezone: str(),
    retentionDays: nullable(int()),
    createdAt: dateTime(),
    memberCount: int(),
    linkCount: int(),
    domainCount: int(),
    campaignCount: int(),
  }),
  AdminDomain: obj({
    id: str(),
    hostname: str(),
    status: str(),
    isVerified: { type: 'boolean' },
    isDefault: { type: 'boolean' },
    workspaceId: nullable(str()),
    createdAt: dateTime(),
    shared: { type: 'boolean' },
  }),
  AdminLink: obj({
    id: str(),
    workspaceId: str(),
    slug: str(),
    destinationUrl: str(),
    isActive: { type: 'boolean' },
    expiresAt: nullable(dateTime()),
    createdAt: dateTime(),
    hostname: str(),
    hasPassword: { type: 'boolean' },
  }),
  FailedJob: obj({
    id: nullable(str()),
    name: str(),
    attemptsMade: int(),
    failedReason: nullable(str()),
    createdAt: dateTime(),
    failedAt: nullable(dateTime()),
    summary: { type: 'object' },
  }),
  QueueCounts: {
    type: 'object',
    additionalProperties: { type: 'object', additionalProperties: int() },
  },
};

/** `{ success: true, data }` */
export const envelope = (data: S): S => ({
  type: 'object',
  properties: { success: { const: true }, data },
  required: ['success', 'data'],
  additionalProperties: false,
});

/** `{ success: true, data: [...], nextCursor }` */
export const paged = (item: S): S => ({
  type: 'object',
  properties: {
    success: { const: true },
    data: { type: 'array', items: item },
    nextCursor: nullable(str()),
    /** Present on lists where counting is cheap (users, workspaces, teams). */
    total: { type: 'integer', minimum: 0 },
  },
  required: ['success', 'data', 'nextCursor'],
  additionalProperties: false,
});

export const ref = (name: string): S => ({ $ref: `#/components/schemas/${name}` });
