export type ErrorCode =
  | 'VALIDATION_ERROR' | 'UNAUTHENTICATED' | 'FORBIDDEN' | 'NOT_FOUND' | 'CONFLICT'
  | 'RATE_LIMITED' | 'CSRF_INVALID' | 'FEATURE_DISABLED' | 'INTERNAL_ERROR'
  | 'INVALID_CREDENTIALS' | 'EMAIL_TAKEN' | 'SLUG_TAKEN' | 'SLUG_RESERVED'
  | 'LINK_NOT_FOUND' | 'DOMAIN_NOT_FOUND' | 'DOMAIN_TAKEN' | 'WORKSPACE_NOT_FOUND';

const STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400, UNAUTHENTICATED: 401, INVALID_CREDENTIALS: 401, FORBIDDEN: 403,
  CSRF_INVALID: 403, FEATURE_DISABLED: 403, NOT_FOUND: 404, LINK_NOT_FOUND: 404,
  DOMAIN_NOT_FOUND: 404, WORKSPACE_NOT_FOUND: 404, CONFLICT: 409, EMAIL_TAKEN: 409,
  SLUG_TAKEN: 409, SLUG_RESERVED: 409, DOMAIN_TAKEN: 409, RATE_LIMITED: 429, INTERNAL_ERROR: 500,
};

export class AppError extends Error {
  readonly status: number;
  constructor(readonly code: ErrorCode, message: string, readonly details?: unknown) {
    super(message);
    this.status = STATUS[code];
  }
}
